package ar.com.cablevision.common.wd2k.constant;

public enum CableModemConstants {

    IDCABLEMODEM_COLUMN("IDCABLEMODEM"),
    IDEMPRESA_COLUMN("IDEMPRESA"),
    IDCLIENTE_COLUMN("IDCLIENTE"),
    IDPRODUCTO_COLUMN("IDPRODUCTO"),
    IDSERVICIO_COLUMN("IDSERVICIO"),
    IDSERVICIOPADRE_COLUMN("IDSERVICIOPADRE"),
    IDPRODUCTOPADRE_COLUMN("IDPRODUCTOPADRE"),
    IDVENTA_COLUMN("IDVENTA"),
    IDPROMOTOR_COLUMN("IDPROMOTOR"),
    MACADDRESS_COLUMN("MACADDRESS"),
    IPFIJA_COLUMN("IPFIJA"),
    IP_COLUMN("IP"),
    POLICY_COLUMN("POLICY"),
    CANTPCS_COLUMN("CANTPCS"),
    HUB_COLUMN("HUB"),
    NODO_COLUMN("NODO"),
    IDCMTS_COLUMN("IDCMTS"),
    DOWNSTREAM_COLUMN("DOWNSTREAM"),
    UPSTREAM_COLUMN("UPSTREAM"),
    MACPC_COLUMN("MACPC"),
    FECHAALTA_COLUMN("FECHAALTA"),
    FECHAACTIVACION_COLUMN("FECHAACTIVACION"),
    TAGPROVEEDOR_COLUMN("TAGPROVEEDOR"),
    VENCIMIENTO_COLUMN("VENCIMIENTO"),
    DISABLED_COLUMN("DISABLED"),
    CALIDAD_COLUMN("CALIDAD"),
    IDFABRICANTE_COLUMN("IDFABRICANTE"),
    IDVERSION_COLUMN("IDVERSION"),
    FECHAMODIF_COLUMN("FECHAMODIF"),
    IPCM_COLUMN("IPCM"),
    FECHABLOQUEOVELOCIDAD_COLUMN("FECHABLOQUEOVELOCIDAD"),
    IDMENSAJE_COLUMN("IDMENSAJE"),
    FECHAVENCIMIENTO_COLUMN("FECHAVENCIMIENTO"),
    IDCALLEAS_COLUMN("IDCALLEAS"),
    NUMERO_COLUMN("NUMERO"),
    NROMANZANA_COLUMN("NROMANZANA"),
    ZONA_COLUMN("ZONA"),
    IDVENTAPADRE_COLUMN("IDVENTAPADRE"),
    IDPRODUCTO2_COLUMN("IDPRODUCTO2"),
    IDPRODUCTOPADRE2_COLUMN("IDPRODUCTOPADRE2"),
    PASSWORDCHECK_COLUMN("PASSWORDCHECK"),
    CANTEXTPRIVADAS_COLUMN("CANTEXTPRIVADAS"),
    IDTIPOCM_COLUMN("IDTIPOCM"),
    IDCUENTA_COLUMN("IDCUENTA"),
    RED_COLUMN("RED"),
    MGT_COLUMN("MGT"),
    NODO_4_COLUMN("NODO_4"),
    IDCOMPANIA_COLUMN("IDCOMPANIA"),
    CANTLINEAS_COLUMN("CANTLINEAS"),
    MODO_COLUMN("MODO"),
    SM_PACKAGEID_COLUMN("SM_PACKAGEID"),
    NET_COLUMN("NET"),
    MOTIVODESACTIVACION_COLUMN("MOTIVODESACTIVACION"),
    VLAN_COLUMN("VLAN"),
    IDTIPOIP_COLUMN("IDTIPOIP"),
    SECONDSSID_COLUMN("SECONDSSID"),

    MACADRESSES_NAMED_PARAMETER("macAddresses"),

    FIND_ALL_QUERY("SELECT * FROM \"INTRAWAY\".\"SRV_CABLEMODEMS\""),
    FIND_BY_ID_QUERY("SELECT * FROM \"INTRAWAY\".\"SRV_CABLEMODEMS\" WHERE IDLEASE=?"),
    FIND_IDCLIENTS_BY_MACADDRESS_QUERY("SELECT MACADDRESS, IDCLIENTE FROM \"INTRAWAY\".\"SRV_CABLEMODEMS\" WHERE MACADDRESS IN (:macAddresses)");


    private final String value;

    CableModemConstants(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}


